const TYPES = {
  // Repositories
  IUserRepository: Symbol.for("IUserRepository"),
  IPostRepository: Symbol.for("IPostRepository"),
  IOtpRepository: Symbol.for("IOtpRepository"),
  ICommentRepository: Symbol.for("ICommentRepository"),
  IConversationRepository: Symbol.for("IConversationRepository"),
  IFollowRepository: Symbol.for("IFollowRepository"),
  ILikeRepository: Symbol.for("ILikeRepository"),
  IMessageRepository: Symbol.for("IMessageRepository"),
  IReportRepository: Symbol.for("IReportRepository"),
  InteractionRepository: Symbol.for("InteractionRepository"),

  // Services
  IPasswordHasher: Symbol.for("IPasswordHasher"),
  ITokenService: Symbol.for("ITokenService"),
  IFileStorageService: Symbol.for("IFileStorageService"),
  IMailService: Symbol.for("IMailService"),
  IOtpService: Symbol.for("IOtpService"),
  IExternalAuthService: Symbol.for("IExternalAuthService"),
  INotificationService: Symbol.for("INotificationService"),

  // Use Cases
  ICreateUser: Symbol.for("ICreateUser"),
  ILoginUser: Symbol.for("ILoginUser"),
  ISignInWithGoogle: Symbol.for("ISignInWithGoogle"),
  IAdminLogin: Symbol.for("IAdminLogin"),
  IAddComment: Symbol.for("IAddComment"),
  ICreateConversation: Symbol.for("ICreateConversation"),
  ICreatePost: Symbol.for("ICreatePost"),
  IDeletePost: Symbol.for("IDeletePost"),
  IEditPost: Symbol.for("IEditPost"),
  IGetAdminPosts: Symbol.for("IGetAdminPosts"),
  IGetAdminUsers: Symbol.for("IGetAdminUsers"),
  IGetComments: Symbol.for("IGetComments"),
  IGetConversation: Symbol.for("IGetConversation"),
  IGetConversations: Symbol.for("IGetConversations"),
  IGetRecommendedPosts: Symbol.for("IGetRecommendedPosts"),
  IGetFollowList: Symbol.for("IGetFollowList"),
  IGetLikedUsers: Symbol.for("IGetLikedUsers"),
  IGetMessages: Symbol.for("IGetMessages"),
  IGetPostById: Symbol.for("IGetPostById"),
  IGetSavedPosts: Symbol.for("IGetSavedPosts"),
  IFetchUser: Symbol.for("IFetchUser"),
  IGetUserProfile: Symbol.for("IGetUserProfile"),
  IMarkMessageAsSeen: Symbol.for("IMarkMessageAsSeen"),
  IRefreshToken: Symbol.for("IRefreshToken"),
  IReportTarget: Symbol.for("IReportTarget"),
  ISearchContent: Symbol.for("ISearchContent"),
  ISendMessage: Symbol.for("ISendMessage"),
  ISendVerificationEmail: Symbol.for("ISendVerificationEmail"),
  ISuggestUser: Symbol.for("ISuggestUser"),
  IToggleFollow: Symbol.for("IToggleFollow"),
  IToggleLike: Symbol.for("IToggleLike"),
  ITogglePostStatus: Symbol.for("ITogglePostStatus"),
  IToggleSavePost: Symbol.for("IToggleSavePost"),
  IToggleUserStatus: Symbol.for("IToggleUserStatus"),
  IUpdateProfile: Symbol.for("IUpdateProfile"),
  IVerifyOtp: Symbol.for("IVerifyOtp"),
  IRecordInteraction: Symbol.for("IRecordInteraction"),

  // Controllers
  AuthController: Symbol.for("AuthController"),
  PostController: Symbol.for("PostController"),
  CommentController: Symbol.for("CommentController"),
  ConversationController: Symbol.for("ConversationController"),
  FollowController: Symbol.for("FollowController"),
  LikeController: Symbol.for("LikeController"),
  ProfileController: Symbol.for("ProfileController"),
  ReportController: Symbol.for("ReportController"),
  SearchController: Symbol.for("SearchController"),
  AdminController: Symbol.for("AdminController"),
  SocketController: Symbol.for("SocketController"),
  CallController: Symbol.for("CallController"),

  // Constants
  SocketServer: Symbol.for("SocketServer"),
  SocketActiveUsers: Symbol.for("SocketActiveUsers"),
};

export { TYPES };
