const TYPES = {
  // Repositories
  IUserRepository: Symbol.for("IUserRepository"),
  IPostRepository: Symbol.for("IPostRepository"),
  IOtpRepository: Symbol.for("IOtpRepository"),
  ICommentRepository: Symbol.for("ICommentRepository"),
  IConversationRepository: Symbol.for("IConversationRepository"),
  IFollowRepository: Symbol.for("IFollowRepository"),
  ILikeRepository: Symbol.for("ILikeRepository"),
  IMessageRepository: Symbol.for("IMessageRepository"),
  IReportRepository: Symbol.for("IReportRepository"),
  InteractionRepository: Symbol.for("InteractionRepository"),

  // Services
  IPasswordHasher: Symbol.for("IPasswordHasher"),
  ITokenService: Symbol.for("ITokenService"),
  IFileStorageService: Symbol.for("IFileStorageService"),
  IMailService: Symbol.for("IMailService"),
  IOtpService: Symbol.for("IOtpService"),

  // Use Cases
  CreateUser: Symbol.for("CreateUser"),
  LoginUser: Symbol.for("LoginUser"),
  SignInWithGoogle: Symbol.for("SignInWithGoogle"),
  AdminLogin: Symbol.for("AdminLogin"),
  AddComment: Symbol.for("AddComment"),
  CreateConversation: Symbol.for("CreateConversation"),
  CreatePost: Symbol.for("CreatePost"),
  DeletePost: Symbol.for("DeletePost"),
  EditPost: Symbol.for("EditPost"),
  GetAdminPosts: Symbol.for("GetAdminPosts"),
  GetAdminUsers: Symbol.for("GetAdminUsers"),
  GetComments: Symbol.for("GetComments"),
  GetConversationId: Symbol.for("GetConversationId"),
  GetConversations: Symbol.for("GetConversations"),
  GetRecommendedPosts: Symbol.for("GetRecommendedPosts"),
  GetFollowList: Symbol.for("GetFollowList"),
  GetLikedUsers: Symbol.for("GetLikedUsers"),
  GetMessages: Symbol.for("GetMessages"),
  GetPostById: Symbol.for("GetPostById"),
  GetSavedPosts: Symbol.for("GetSavedPosts"),
  GetUserDataForForm: Symbol.for("GetUserDataForForm"),
  GetUserProfile: Symbol.for("GetUserProfile"),
  MarkMessageAsSeen: Symbol.for("MarkMessageAsSeen"),
  RefreshToken: Symbol.for("RefreshToken"),
  ReportTarget: Symbol.for("ReportTarget"),
  SearchContent: Symbol.for("SearchContent"),
  SendMessage: Symbol.for("SendMessage"),
  SendVerificationEmail: Symbol.for("SendVerificationEmail"),
  ToggleFollow: Symbol.for("ToggleFollow"),
  ToggleLike: Symbol.for("ToggleLike"),
  TogglePostStatus: Symbol.for("TogglePostStatus"),
  ToggleSavePost: Symbol.for("ToggleSavePost"),
  ToggleUserStatus: Symbol.for("ToggleUserStatus"),
  UpdateProfile: Symbol.for("UpdateProfile"),
  VerifyOtp: Symbol.for("VerifyOtp"),
  RecordInteraction: Symbol.for("RecordInteraction"),
};

export { TYPES };
